spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal/rinha
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  devtools:
    remote:
      restart:
        enabled: false
  threads:
    virtual:
      enabled: true
server:
  error:
    whitelabel:
      enabled: false
