spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://host.docker.internal/rinha}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
  jackson:
    deserialization:
      accept-float-as-int: false
  threads:
    virtual:
      enabled: true
