spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: rinha-hikari
      maximum-pool-size: 20
  devtools:
    remote:
      restart:
        enabled: false
  threads:
    virtual:
      enabled: true
server:
  error:
    whitelabel:
      enabled: false
  undertow:
    threads:
      worker: 200
