spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://host.docker.internal/rinha}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      accept-float-as-int: false
  devtools:
    remote:
      restart:
        enabled: false
  threads:
    virtual:
      enabled: true
server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
